# Generated by Django 5.2.3 on 2025-06-20 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='UNNAMED', max_length=100)),
                ('language', models.CharField(choices=[('python', 'Python'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++')], max_length=30)),
                ('code', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightedSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_code', models.TextField()),
                ('snippet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted', to='snippets.snippet')),
            ],
        ),
    ]
