# Generated by Django 5.2.3 on 2025-06-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(to='snippets.tag'),
        ),
    ]
